name: Quality Check

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependências
        run: |
          npm install
          cd backend
          npm install

      - name: Executar quality
        run: |
          cd backend
          npm run quality
